### ISSUE TITLE
Use Dialogs for Filter forms

### ISSUE THREAD

**Issue by kadosh** [unosquare/tubular2#18]
Currently, filter popups are not being closed when executing the Search action and you can have more than one popup opened at the same time.

**Comment by devmanusanram** [comment]
Trying to fix the hiding of the filter popups, some observations were made:
- The form inside can terminate the popover by simply clicking on the submit button.
- The popover CAN be terminated by unfocusing any of the form elements or the form itself. Currently looking for a way to automatically set focus to the form or it's elements.
- Popover form DOESN'T let user write values to filter the data on a column.

**Comment by devmanusanram** [comment]
Implemented a toggle component to toggle the popovers on the main screen.
However, though the toggle variables change, the popovers either, do not show on screen neither they disappear when another popover is clicked.
This was planned to be achieved through events sent by the toggle component.

**Comment by geoperez** [comment]
Please change to Dialogs and use dev branch.
