### ISSUE TITLE
Use Tubular Common

### ISSUE THREAD

**Issue by geoperez** [unosquare/tubular2#25]
Use Tubular Common and remove models from here.

**Comment by Serk352** [comment]
Trying to accomplish this, i found a couple of problems:
The tubular-common library doesn't have all the necessary functions to make it work as we want, for example: 
In the class ColumnModel we don´t have the functions:
*getInputType()
*getOperators()
 
also we need the properties:
*filterMode
*direction (diferent of the sortdirection porperty)
*isMultiSort


![dferences in colummodel class](https://user-images.githubusercontent.com/25519413/43861576-dff4ec24-9b1c-11e8-94b5-86bf88bbce14.PNG)

**Comment by geoperez** [comment]
* `getOperators `should be defined in Tubular Common, in fact I noticed that Tubular React has a similar [implementation](https://github.com/unosquare/tubular-react/blob/master/src/DataGrid/OperatorsDropdown.tsx#L12). I'm going to extract this to Tubular Common and let you know when it's done. Please continue with another issue and good catch.
* `getInputType `is not valid, see `FilterMode `below.
* `Multisort `is a user interaction state, not a column property, remove it and implement in another way. Check Tubular React if you need more information.
* `FilterMode `is useless, we need to remove this from code.
* `Direction `is the same as `SortDirection`. If the current model is using both, please adjust the code to use only one.

**Comment by geoperez** [comment]
Closing by now.
