### ISSUE TITLE
Upgrade documentation

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/tubular2#35]
**Is your feature request related to a problem? Please describe.**
The application was upgraded to use angular 4, but the readme still showing the information of the previous one.

**Describe the solution you'd like**
Upgrade documentation.

**Additional context**
![image](https://user-images.githubusercontent.com/26309079/52821398-4f858200-3074-11e9-86b2-5dd7d95d0321.png)

**Comment by geoperez** [comment]
Also, you need to fix the web site https://unosquare.github.io/tubular2/
