### ISSUE TITLE
Update to Angular8

### ISSUE THREAD

**Issue by xquetzalcoatl** [unosquare/tubular2#37]
**DESCRIPTION**
Update Tubular2 to the latest version of Angular.
There are two options to solve this issue:

- [ ] Update the current version of tubular2.

- [x] Start a new solution from scratch.

**EXPECTED BEHAVIOUR**
All main functionality for Tubular2 must work now with Angular8.

Estimated time: 5 hours, 30 minutes

**Comment by devmanusanram** [comment]
As requested by @geoperez and @kadosh, a solution from scratch is the best approach to solve this issue.

**Comment by devmanusanram** [comment]
These issue will remain on hold for now.

**Comment by geoperez** [comment]
Status?
